name: Deploy main to demo

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Identity 🔧
        run: |
          git config --global user.name "alfianchii"
          git config --global user.email "pianaee379@gmail.com"

      - name: Deploy 🚀
        run: |
          npm install
          npm run deploy
